"""Offline HD map extraction. Runtime has no image-processing dependency.

Run: python scripts/build-hd-maps.py (requires Pillow).
Original AOSP source images are never modified.
"""
import argparse
import base64
import io
import json
import subprocess
from pathlib import Path
from PIL import Image, ImageFilter, ImageOps

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'reference' / 'original-assets'


def canopy_map(pond):
    # Work only within the original usable image, excluding the white column.
    crop = pond.convert('RGB').crop((0, 224, 958, 1024))
    gray = crop.convert('L')
    # Soft dark-tree selection before downsampling, not a black copy of the photo.
    mask = gray.point(lambda p: round(255 * max(0, min(1, (86-p)/66))))
    mask = mask.resize((256, 256), Image.Resampling.BOX)
    return mask.filter(ImageFilter.GaussianBlur(5)).convert('RGB')


def png_bytes(image):
    stream = io.BytesIO()
    image.save(stream, format='PNG', optimize=True)
    return stream.getvalue()


def shadow_map(leaves):
    result = Image.new('RGBA', leaves.size, (255, 255, 255, 0))
    for cell in range(8):
        alpha = leaves.getchannel('A').crop((cell*128, 0, (cell+1)*128, 128))
        alpha = ImageOps.expand(alpha, 8).filter(ImageFilter.GaussianBlur(2.6)).crop((8, 8, 136, 136))
        tile = Image.new('RGBA', (128, 128), 'white')
        tile.putalpha(alpha)
        result.paste(tile, (cell*128, 0))
    return result


def contact_map(leaves):
    # Keep the existing tested contour algorithm in one place, as an offline helper.
    js = "const fs=require('node:fs');const a=require(process.argv[1]).atlas(fs.readFileSync(0));process.stdout.write(Buffer.from(a.data));"
    output = subprocess.run(['node', '-e', js, str(ROOT/'scripts/lib/meniscus.cjs')],
                            input=leaves.tobytes(), capture_output=True, check=True).stdout
    return Image.frombytes('RGBA', (1536, 192), output)


def build(check=False):
    leaves = Image.open(SOURCE / 'leaves.png').convert('RGBA')
    maps = {'canopy': canopy_map(Image.open(SOURCE / 'pond.jpg')),
            'contact': contact_map(leaves), 'shadow': shadow_map(leaves)}
    target = ROOT / 'reference' / 'derived'
    outputs = {target/f'hd-{name}.png': png_bytes(im) for name, im in maps.items()}
    embedded = {name: 'data:image/png;base64,'+base64.b64encode(outputs[target/f'hd-{name}.png']).decode('ascii') for name in maps}
    outputs[ROOT/'wallpaper-hd/maps.js'] = (
        '/* Generated by scripts/build-hd-maps.py; do not hand-edit. Apache-2.0. */\n'
        'const WaterMaps='+json.dumps(embedded, separators=(',', ':'))+';\n').encode('utf-8')
    for path, data in outputs.items():
        if check:
            if not path.exists() or path.read_bytes() != data:
                raise SystemExit(f'Outdated generated map: {path}; run scripts/build-hd-maps.py')
        else:
            path.parent.mkdir(exist_ok=True)
            path.write_bytes(data)
    print(('Verified' if check else 'Built')+' offline canopy, contact and shadow maps; no runtime baking.')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Verify reproducibility without writing files')
    build(parser.parse_args().check)
