"""Offline HD map extraction. Runtime has no image-processing dependency.

Run: python scripts/build-hd-maps.py (requires Pillow).
Original AOSP source images are never modified.
"""
import argparse
import base64
import io
import json
import subprocess
from pathlib import Path
from PIL import Image, ImageFilter, ImageOps

ROOT = Path(__file__).resolve().parents[1]
SETTINGS = json.loads(subprocess.check_output(['node','-e',
    "console.log(JSON.stringify(require(process.argv[1])))",str(ROOT/'wallpaper-hd/settings.js')]))

def smooth(a,b,x):
    t=max(0,min(1,(x-a)/(b-a)))
    return t*t*(3-2*t)


def canopy_map(pond):
    # Work only within the original usable image, excluding the white column.
    p=SETTINGS['light']['canopy']; n=p['resolution']; scale=pond.width/1024
    crop=pond.convert('RGB').crop(tuple(round(v*scale) for v in (0,224,958,1024)))
    # Classify near-neutral black silhouettes, excluding even dark blue sky.
    # Bound offline work while retaining small silhouette openings.
    crop=crop.resize((n*2,n*2),Image.Resampling.LANCZOS)
    mask=Image.new('L',crop.size)
    mask.putdata([round(255*(1-smooth(*p['dark'],max(rgb)))*(1-smooth(*p['chroma'],max(rgb)-min(rgb)))) for rgb in crop.getdata()])
    mask=mask.resize((n,n),Image.Resampling.BOX)
    light=SETTINGS['light']['direction']; height=p['projectionHeight']; zoom=p['scale']
    # Artistic cast-shadow offset away from the key, in image (downward-Y) UVs.
    dx=-light[0]/light[2]*height; dy=light[1]/light[2]*height
    mask=mask.transform((n,n),Image.Transform.AFFINE,
        (1/zoom,0,n*(.5-(.5+dx)/zoom),0,1/zoom,n*(.5-(.5+dy)/zoom)),
        Image.Resampling.BICUBIC,fillcolor=0)
    mask=mask.filter(ImageFilter.GaussianBlur(p['blur']))
    return mask.point(lambda v:round(255*smooth(*p['levels'],v/255))).convert('RGB')


def png_bytes(image):
    stream = io.BytesIO()
    image.save(stream, format='PNG', optimize=True)
    return stream.getvalue()


def shadow_map(leaves):
    # Shadows need less detail than color. Radii remain in original 128px units.
    result = Image.new('RGBA', (2048,512), (255, 255, 255, 0))
    source_cell = leaves.height
    for row,blur in enumerate((3.2,7.2)):
      for cell in range(8):
        alpha = leaves.getchannel('A').crop((cell*source_cell, 0, (cell+1)*source_cell, source_cell))
        alpha = alpha.resize((256,256), Image.Resampling.LANCZOS)
        alpha = ImageOps.expand(alpha, 24).filter(ImageFilter.GaussianBlur(blur)).crop((24, 24, 280, 280))
        tile = Image.new('RGBA', (256, 256), 'white')
        tile.putalpha(alpha)
        result.paste(tile, (cell*256, row*256))
    return result


def contact_map(leaves):
    # Keep the field in its original design coordinates; derive it from HD alpha.
    compact = Image.new('RGBA', (1024,128), (255,255,255,0))
    cell = leaves.height
    for i in range(8):
        alpha = leaves.getchannel('A').crop((i*cell,0,(i+1)*cell,cell)).resize((128,128),Image.Resampling.BOX)
        tile = Image.new('RGBA',(128,128),'white'); tile.putalpha(alpha)
        compact.paste(tile,(i*128,0))
    # Keep the existing tested contour algorithm in one place, as an offline helper.
    js = "const fs=require('node:fs');const a=require(process.argv[1]).atlas(fs.readFileSync(0));process.stdout.write(Buffer.from(a.data));"
    output = subprocess.run(['node', '-e', js, str(ROOT/'scripts/lib/meniscus.cjs')],
                            input=compact.tobytes(), capture_output=True, check=True).stdout
    return Image.frombytes('RGBA', (1536, 192*len(SETTINGS['contact']['poses'])), output)


def build(check=False):
    leaves_path = ROOT/'reference/derived/hd-leaves-4x.png'
    leaves = Image.open(leaves_path).convert('RGBA')
    pond_path=ROOT/'reference/derived/hd-pond-4k.png'
    maps = {'canopy': canopy_map(Image.open(pond_path)),
            'contact': contact_map(leaves), 'shadow': shadow_map(leaves)}
    target = ROOT / 'reference' / 'derived'
    outputs = {target/f'hd-{name}.png': png_bytes(im) for name, im in maps.items()}
    embedded = {name: 'data:image/png;base64,'+base64.b64encode(outputs[target/f'hd-{name}.png']).decode('ascii') for name in maps}
    outputs[ROOT/'wallpaper-hd/maps.js'] = (
        '/* Generated by scripts/build-hd-maps.py; do not hand-edit. Apache-2.0. */\n'
        'const WaterMaps='+json.dumps(embedded, separators=(',', ':'))+';\n').encode('utf-8')
    assets={'pond':'data:image/png;base64,'+base64.b64encode(pond_path.read_bytes()).decode('ascii'),
            'leaves':'data:image/png;base64,'+base64.b64encode(leaves_path.read_bytes()).decode('ascii')}
    outputs[ROOT/'wallpaper-hd/assets.js']=(
        '/* Generated by scripts/build-hd-maps.py. AOSP artwork: NOTICE.txt. */\n'
        'const WaterAssets='+json.dumps(assets,separators=(',',':'))+';\n').encode('utf8')
    for path, data in outputs.items():
        if check:
            if not path.exists() or path.read_bytes() != data:
                raise SystemExit(f'Outdated generated map: {path}; run scripts/build-hd-maps.py')
        else:
            path.parent.mkdir(exist_ok=True)
            path.write_bytes(data)
    print(('Verified' if check else 'Built')+' offline canopy, contact and shadow maps; no runtime baking.')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Verify reproducibility without writing files')
    build(parser.parse_args().check)
